from django.conf import settings

RESULTS_PER_PAGE = getattr(settings, 'LINKCHECK_RESULTS_PER_PAGE', 10000)
EXTERNAL_RECHECK_INTERVAL = getattr(settings, 'LINKCHECK_EXTERNAL_RECHECK_INTERVAL', 86400)
INTERNAL_RECHECK_INTERVAL = getattr(settings, 'LINKCHECK_INTERNAL_RECHECK_INTERVAL', 3600)
MAX_CHECKS_PER_RUN = getattr(settings, 'LINKCHECK_MAX_CHECKS_PER_RUN', -1)