# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkcheck', '0003_alert_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='alert_mails_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('ok', 'None'), ('error', 'Error'), ('untested', 'Not tested')], default='untested', max_length=20),
        ),
    ]
